controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: '/login'
    controller: 'App\Controller\LoginController::login'

logout:
    path: '/logout'
    controller: 'App\Controller\LogoutController::logout'

dashboard:
    path: '/dashboard'
    controller: 'App\Controller\TuteurController::dashboard'

etudiants_list:
    path: '/etudiants'
    controller: 'App\Controller\EtudiantController::index'

etudiant_new:
    path: '/etudiants/new'
    controller: 'App\Controller\EtudiantController::new'

etudiant_edit:
    path: '/etudiants/{id}/edit'
    controller: 'App\Controller\EtudiantController::edit'

etudiant_delete:
    path: '/etudiants/{id}/delete'
    controller: 'App\Controller\EtudiantController::delete'

visites_etudiant:
    path: 'etudiants/{id}/visites'
    controller: 'App\Controller\VisiteController::index'

visite_new:
    path: 'etudiants/{id}/visites/new'
    controller: 'App\Controller\VisiteController::new'

visite_edit:
    path: '/visites/{id}/edit'
    controller: 'App\Controller\VisiteController::edit'

visite_compte_rendu:
    path: '/visites/{id}/compte-rendu'
    controller: 'App\Controller\VisiteController::compteRendu'

visite_pdf:
    path: '/visites/{id}/compte-rendu/pdf'
    controller: 'App\Controller\VisiteController::exportPDF'
    
    
    
    